name: aavs
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Base
  - python
  - mamba
  - pip 
  - poetry
  - pytz
  - tzdata
  - python-dateutil
  - urllib3
  # Scientific
  - numpy
  - scipy
  - xarray
  - ducc0
  # astro
  - astropy
  - astroplan
  - pyerfa
  - casacore
  - python-casacore
  - healpy
  # I/O
  - h5py
  - pyyaml
  - msgpack-numpy
  # test + logging
  - loguru
  - pytest
  - pytest-cov 
  # Docs
  - sphinx
  - sphinx-rtd-theme
  # C/C++ compilation (use conda gcc instead of system, which can be ancient)
  - gcc
  - gxx
  - openmp
